import type { NextPage } from 'next';
import Head from 'next/head';
//State

//Components
import NoteEditor from '../components/Editor';
import NotesList from '../components/NotesList';
import Sidebar from '../components/Sidebar/';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>re:write</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen grid grid-cols-[300px_400px_1fr]">
        <Sidebar />
        <NotesList />
        <NoteEditor />
      </main>
    </>
  );
};

export default Home;
