import { createNextApiHandler } from '@trpc/server/adapters/next';
import type { NextPage } from 'next';
import Head from 'next/head';
import NoteEditor from '../components/NoteEditor';
import NotesList from '../components/NotesList';
import Sidebar from '../components/Sidebar';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>re:write</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen grid grid-cols-6">
        <Sidebar />
        <NotesList />
        <NoteEditor />
      </main>
    </>
  );
};

export default Home;
